# domain/ports.py
from typing import Protocol, Optional
from .entities import MapGraph

class MapProviderPort(Protocol):
    def load(self) -> MapGraph: ...

class StateRepositoryPort(Protocol):
    def init_schema(self) -> None: ...
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, val: str) -> None: ...
    def close(self) -> None: ...
