# domain/ports.py
from typing import Protocol, Optional, Set, List
from .entities import MapGraph, Player, Character

class MapProviderPort(Protocol):
    def load(self) -> MapGraph: ...

class StateRepositoryPort(Protocol):
    def init_schema(self) -> None: ...
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, val: str) -> None: ...
    def close(self) -> None: ...

class PlayerRepositoryPort(Protocol):
    def init_schema(self) -> None: ...
    def get_player(self, user_id: str) -> Optional[Player]: ...
    def upsert_player(self, p: Player) -> None: ...
    # 角色相关
    def list_owned_char_names(self, user_id: str) -> Set[str]: ...
    def add_character(self, user_id: str, char_name: str, level: int, obtained_at: int) -> None: ...
